---
before_install:
  - time perl ./maint-travis-ci/sterilize_env.pl
branches:
  only:
    - build/master
    - releases
env:
  matrix:
    - STERILIZE_ENV=0
    - STERILIZE_ENV=1
install:
  - time cpanm --quiet --notest --mirror http://cpan.metacpan.org/ --installdeps .
language: perl
perl:
  - 5.16
  - 5.14
  - 5.18
  - 5.19
